apiVersion: v1
kind: ConfigMap
metadata:
  name: order-processing-ms-config
  namespace: order-processing-ms
data:
  ASPNETCORE_URLS: "http://+:5000"
  ASPNETCORE_ENVIRONMENT: "Development"
  
  LOGIN_MS_URL: "https://localhost:8080"
  ORDER_MS_URL: "https://localhost:8082"
  PAYMENT_MS_URL: "https://localhost:8083"


