apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processing-ms-webapi-deployment
  namespace: order-processing-ms
  labels:
    app: order-processing-ms-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processing-ms-webapi
  template:
    metadata:
      labels:
        app: order-processing-ms-webapi
    spec:
      containers:
      - name: order-processing-ms-webapi
        image: goncalvesc97/fiap-tc-4-order-processing-ms:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5000"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"

        # Configuração do ambiente de banco de dados 

        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: order-processing-ms-secret
              key: DB_CONNECTION_STRING

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: order-processing-ms-secret
              key: DB_NAME

        # Configuração da chave de autenticação da API

        - name: API_AUTHENTICATION_KEY
          valueFrom:
            secretKeyRef:
              name: order-processing-ms-secret
              key: API_AUTH_TOKEN

        # Configuração dos caminhos de microsserviços

        - name: LOGIN_MS_URL
          valueFrom:
            configMapKeyRef:
              name: order-processing-ms-config
              key: LOGIN_MS_URL

        - name: ORDER_MS_URL
          valueFrom:
            configMapKeyRef:
              name: order-processing-ms-config
              key: ORDER_MS_URL

        - name: PAYMENT_MS_URL
          valueFrom:
            configMapKeyRef:
              name: order-processing-ms-config
              key: PAYMENT_MS_URL