apiVersion: v1
kind: Service
metadata:
  name: order-processing-ms-webapi-service
  namespace: order-processing-ms
spec:
  type: LoadBalancer
  selector:
    app: order-processing-ms-webapi
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 5000